import { } from 'jasmine';
import { NO_ERRORS_SCHEMA, } from '@angular/core';
import { TestBed, ComponentFixture } from '@angular/core/testing';
import { DialogRef } from 'common/services';
import { TollViolationsModalComponent, InjectionValues } from './tollViolationsModal.component';

import { Violation, ViolationInvoice } from 'violations/interfaces';
import { ENVIRON_CONFIG } from 'common/upgrades';
import { IViolation } from 'violationsCommon/interfaces';

describe('TollViolationsModalComponent', () => {

    let fixture: ComponentFixture<TollViolationsModalComponent>;
    let component: TollViolationsModalComponent;

    let dialogRef: DialogRef<InjectionValues>;
    let environmentConfig;

    const invoices: ViolationInvoice[] = [
        {
            agencyName: 'h',
            mobileAgencyName: 'h',
            dueDate: '2018-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'f',
            mobileAgencyName: 'f',
            dueDate: null,
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'h',
            mobileAgencyName: 'h',
            dueDate: '2016-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'm',
            mobileAgencyName: 'm',
            dueDate: '2016-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'm',
            mobileAgencyName: 'm',
            dueDate: null,
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'h',
            mobileAgencyName: 'h',
            dueDate: '2018-02-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 't',
            mobileAgencyName: 't',
            dueDate: '2021-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 't',
            mobileAgencyName: 't',
            dueDate: null,
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 't',
            mobileAgencyName: 't',
            dueDate: 'fake Date',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        }
    ];

    const sortedInvoices: ViolationInvoice[] = [
        {
            agencyName: 'h',
            mobileAgencyName: 'h',
            dueDate: '2016-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'h',
            mobileAgencyName: 'h',
            dueDate: '2018-02-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'h',
            mobileAgencyName: 'h',
            dueDate: '2018-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'f',
            mobileAgencyName: 'f',
            dueDate: null,
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'm',
            mobileAgencyName: 'm',
            dueDate: null,
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 'm',
            mobileAgencyName: 'm',
            dueDate: '2016-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 't',
            mobileAgencyName: 't',
            dueDate: null,
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 't',
            mobileAgencyName: 't',
            dueDate: 'fake Date',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        },
        {
            agencyName: 't',
            mobileAgencyName: 't',
            dueDate: '2021-07-08T00:00:00',
            openAdminFeesDue: 0,
            openTollAmountDue: 0,
            openCollectionFeesDue: 0,
            openOtherFeesDue: 0,
            agencyId: 0,
            mailedDate: '',
            status: '',
            invoiceId: '',
            invoiceNum: '',
            invoiceDueAfterDiscount: 0,
            invoiceDueBeforeDiscount: 0,
            invoiceLevelDiscount: 0,
            originalTollAmount: 0,
            originalAdminFees: 0,
            originalCollectionFees: 0,
            originalOtherFees: 0,
            originalInvoiceTotal: 0,
            previouslyPaid: 0,
            newEzTagAccountInvoiceDiscountAmt: 0,
            newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
            violations: [{} as Violation],
            paymentAmount: 0,
            excusalAmt: 0,
            hasCAOFineEstimate: false,
            caoFineEstimate: 0,
        }
    ];

    const unInvoiced: IViolation[] = [
        {
            tollAmount: 0,
            violationId: 0,
            agencyName: 'f',
            location: 'test location',
            violationDate: null,
            agencyId: 0,
            mobileAgencyName: '',
            originalTollAmount: 0,
            paymentAmount: 0
        },
        {
            tollAmount: 0,
            violationId: 0,
            agencyName: 'h',
            location: 'test location',
            violationDate: '2016-07-08T00:00:00',
            agencyId: 0,
            mobileAgencyName: '',
            originalTollAmount: 0,
            paymentAmount: 0
        },
        {
            tollAmount: 0,
            violationId: 0,
            agencyName: 'm',
            location: 'test location',
            violationDate: '2016-07-08T00:00:00',
            agencyId: 0,
            mobileAgencyName: '',
            originalTollAmount: 0,
            paymentAmount: 0
        },
        {
            tollAmount: 0,
            violationId: 0,
            agencyName: 'h',
            location: 'test location',
            violationDate: '2018-07-08T00:00:00',
            agencyId: 0,
            mobileAgencyName: '',
            originalTollAmount: 0,
            paymentAmount: 0
        }
    ];


    beforeEach(async () => {
        environmentConfig = {
            isMergeMATandVioOn: false
        };
        dialogRef = {
            close: jasmine.createSpy('close') as ((InjectionValues) => void),
            data: {
                tollSummaryDetails: { totalViolationsDue: '1' },
                plate: {
                    previouslyPaidInvoices: [{
                        agencyName: 'm',
                        dueDate: null,
                        openAdminFeesDue: 0,
                        openTollAmountDue: 0,
                        openCollectionFeesDue: 0,
                        openOtherFeesDue: 0,
                        agencyId: 0,
                        mailedDate: '',
                        status: '',
                        invoiceId: '',
                        invoiceNum: '',
                        invoiceDueAfterDiscount: 0,
                        invoiceDueBeforeDiscount: 0,
                        invoiceLevelDiscount: 0,
                        originalTollAmount: 0,
                        originalAdminFees: 0,
                        originalCollectionFees: 0,
                        originalOtherFees: 0,
                        originalInvoiceTotal: 0,
                        previouslyPaid: 0,
                        newEzTagAccountInvoiceDiscountAmt: 0,
                        newEzTagAccountInvoiceDueAfterDiscountAmt: 0,
                        violations: [{} as Violation],
                        paymentAmount: 0,
                        excusalAmt: 0,
                    }],
                    invoices,
                    uninvoicedViolations: unInvoiced,
                    discountProgramCode: 0,
                    violatorID: 0,
                    totalFeesDiscounted: 0,
                    serviceFee: 0,
                    plateDueAfterDiscount: 0,
                    plateDueBeforeDiscount: 0,
                    isNewEzTagAccountEligibile: true,
                    newEzTagAccountDiscount: 0,
                    newEzTagAccountStartingBalance: 0,
                    newEzTagAccountEZTagFee: 0,
                    newEzTagAccountPlateTotal: 0,
                    hasPaymentPlan: false,
                    licensePlate: '',
                    licenseState: '',
                    totalPaymentAmount: 0,
                    totalUninvoicedAmount: 0,
                    totalInvoicedAmount: 0,
                    accountVehicleId: 0,
                    totalSelected: 0,
                    remainingBalance: 0
                }
            } as InjectionValues
        } as DialogRef<InjectionValues>;

        await TestBed
            .configureTestingModule({
                declarations: [
                    TollViolationsModalComponent
                ],
                schemas: [NO_ERRORS_SCHEMA],
                providers: [
                    { provide: DialogRef, useFactory: () => dialogRef },
                    { provide: ENVIRON_CONFIG, useFactory: () => environmentConfig }
                ]
            })
            .compileComponents();


        fixture = TestBed.createComponent(TollViolationsModalComponent);
        component = fixture.debugElement.componentInstance;

    });

    describe('canary', () => {

        it('should pass', async () => {

            expect(true).toBe(true);
        });
    });

    describe('close', () => {
        it('should call dialogRef Close', () => {
            //Act
            component.close();

            //Assert
            expect(dialogRef.close).toHaveBeenCalled();
        });
    });

    it('should set unInvoiced to empty if frp3 is toggled off', () => {
        component.ngOnInit();
        expect(component.unInvoiced.length).toBe(0);
    });

    it('can sort invoices correctly', () => {
        spyOn(component as any, 'sortInvoices').and.callThrough();

        component.ngOnInit();
        expect(component['sortInvoices']).toHaveBeenCalled();

        expect(component.invoices[0].agencyName).toBe(sortedInvoices[0].agencyName);
        expect(component.invoices[1].agencyName).toBe(sortedInvoices[1].agencyName);
        expect(component.invoices[2].agencyName).toBe(sortedInvoices[2].agencyName);
        expect(component.invoices[3].agencyName).toBe(sortedInvoices[3].agencyName);
        expect(component.invoices[4].agencyName).toBe(sortedInvoices[4].agencyName);
        expect(component.invoices[5].agencyName).toBe(sortedInvoices[5].agencyName);
        expect(component.invoices[6].agencyName).toBe(sortedInvoices[6].agencyName);
        expect(component.invoices[7].agencyName).toBe(sortedInvoices[7].agencyName);
        expect(component.invoices[8].agencyName).toBe(sortedInvoices[8].agencyName);
        expect(component.invoices[0].dueDate).toBe(sortedInvoices[0].dueDate);
        expect(component.invoices[1].dueDate).toBe(sortedInvoices[1].dueDate);
        expect(component.invoices[2].dueDate).toBe(sortedInvoices[2].dueDate);
        expect(component.invoices[3].dueDate).toBeNull();
        expect(component.invoices[4].dueDate).toBeNull();
        expect(component.invoices[5].dueDate).toBe(sortedInvoices[5].dueDate);
        expect(component.invoices[6].dueDate).toBeNull();
        expect(component.invoices[7].dueDate).toBe(sortedInvoices[7].dueDate);
        expect(component.invoices[8].dueDate).toBe(sortedInvoices[8].dueDate);
    });

});
